export const useViu = () => {
  const viu: Product = {
    title: "Viu",
    logo: "https://www.viu.com/ott/1viu-static/assets/logo/logo_icon.svg",
    note: [
      "- Full Garansi",
      "- Akun dari seller tinggal pakai",
      "- Bisa login All Device (Hp, Laptop, TV, Tablet, dll)",
      "- Viu Private Biasa terkadang kena limit meskipun private",
      "- Viu Private Antilimit lebih aman dan nyaman",
      "- Akun privat bisa sampai 5 device dan bebas atur settingan akun",
    ],
    type: [
      {
        name: "Private Biasa",
        count: 0,
        list: [
          {
            name: "1 Bulan",
            stock_price: 7,
            official_price: 0,
            real_price: 0,
            sell_price: 0,
            profit: 0,
            is_shown: true,
          },
          {
            name: "2 Bulan",
            stock_price: 12,
            official_price: 0,
            real_price: 0,
            sell_price: 0,
            profit: 0,
            is_shown: true,
          },
          {
            name: "3 Bulan",
            stock_price: 15,
            official_price: 0,
            real_price: 0,
            sell_price: 0,
            profit: 0,
            is_shown: true,
          },
          {
            name: "6 Bulan",
            stock_price: 17,
            official_price: 0,
            real_price: 0,
            sell_price: 0,
            profit: 0,
            is_shown: true,
          },
          {
            name: "1 Tahun",
            stock_price: 25,
            official_price: 0,
            real_price: 0,
            sell_price: 0,
            profit: 0,
            is_shown: true,
          },
        ],
      },
      {
        name: "Private Antilimit",
        count: 0,
        list: [
          {
            name: "1 Bulan",
            stock_price: 12,
            official_price: 0,
            real_price: 0,
            sell_price: 0,
            profit: 0,
            is_shown: true,
          },
          {
            name: "2 Bulan",
            stock_price: 17,
            official_price: 0,
            real_price: 0,
            sell_price: 0,
            profit: 0,
            is_shown: true,
          },
          {
            name: "3 Bulan",
            stock_price: 19,
            official_price: 0,
            real_price: 0,
            sell_price: 0,
            profit: 0,
            is_shown: true,
          },
          {
            name: "6 Bulan",
            stock_price: 34,
            official_price: 100,
            real_price: 0,
            sell_price: 0,
            profit: 0,
            is_shown: true,
          },
          {
            name: "1 Tahun",
            stock_price: 40,
            official_price: 200,
            real_price: 0,
            sell_price: 0,
            profit: 0,
            is_shown: true,
          },
        ],
      },
    ],
  };
  return {
    viu,
  };
};
